#!/usr/bin/env bash

source "$(dirname "$0")/ft-util/ft_util_inc_var"

SRC_DIR="/usr/local/src"
PKG_REPO_URL="repo.zabbix.com/zabbix/5.0/debian"
PKG_ZBX_URL="https://${PKG_REPO_URL}/pool/main/z/zabbix-release"
PKG_ZBX_NAME="zabbix-release"
ZBX_CONF="/etc/zabbix/zabbix_agent2.conf"
ZBX_CONF_D="/etc/zabbix/zabbix_agent2.d"

LOG_DEBUG=true

$S_LOG -d $S_NAME "Start $S_NAME $*"

if $S_DIR_PATH/ft-util/ft_util_pkg "zabbix-agent"
then
    $S_LOG -s warn -d $S_NAME "Zabbix Agent is already installed and need to be replaced by Zabbix Agent2"

    $S_LOG -s warn -d $S_NAME "Removing zabbix-agent"

    DEBIAN_FRONTEND=noninteractive apt-get remove -qq --purge zabbix-agent < /dev/null > /dev/null
    $S_LOG -s $? -d $S_NAME "apt-get remove -qq --purge zabbix-agent returned EXIT_CODE=$?"

    $S_DIR_PATH/ft-util/ft_util_pkg -u -i "zabbix-agent2" || exit 1
fi

if $S_DIR_PATH/ft-util/ft_util_pkg "zabbix-agent2"
then
    $S_LOG -d $S_NAME "Zabbix Agent 2 is already installed"

else

    #############################
    ## GET CORRECT PACKAGE     ##
    #############################

    # Overide for Raspberry Pi OS
    if cat /etc/os-release | grep 'raspbian' > /dev/null
    then
        $S_LOG -d $S_NAME "Raspberry Pi OS Detected"
        PKG_REPO_URL="repo.zabbix.com/zabbix/5.0/raspbian" 
        PKG_ZBX_URL="http://${PKG_REPO_URL}/pool/main/z/zabbix-release"
    fi

    case $(sed -rn 's/([0-9]+)\.[0-9]+/\1/p' /etc/debian_version) in
        9)  
            PKG_ZBX_NAME="${PKG_ZBX_NAME}_5.0-1+stretch_all.deb"
            ;;
        10) 
            PKG_ZBX_NAME="${PKG_ZBX_NAME}_5.0-1+buster_all.deb"
            ;;
        11) 
            PKG_ZBX_NAME="${PKG_ZBX_NAME}_5.0-1+bullseye_all.deb"
            ;;
        *) 
            $S_LOG -s warn -d $S_NAME "Version of Debian not supported by the script."
            exit 1 
            ;;
    esac

    cd $SRC_DIR
    if [ -e ${PKG_ZBX_NAME} ]
    then
        $S_LOG -s $? -d $S_NAME "Package ${PKG_ZBX_NAME} found in $SRC_DIR"
    else
        wget --quiet ${PKG_ZBX_URL}/${PKG_ZBX_NAME}
        $S_LOG -s $? -d $S_NAME "Download of ${PKG_ZBX_URL}/${PKG_ZBX_NAME} returned code $?"
    fi

    #############################
    ## REMOVE ZABBIX AGENT 2   ##
    #############################
    $S_LOG -d $S_NAME "Removing Zabbix Agent 2"

    DEBIAN_FRONTEND=noninteractive apt-get remove -qq --purge zabbix-agent* < /dev/null > /dev/null
    $S_LOG -s $? -d $S_NAME "apt-get remove -qq --purge zabbix-agent*"

    dpkg -r zabbix-release > /dev/null
    $S_LOG -s $? -d $S_NAME "dpkg -r zabbix-release"

    #############################
    ## INSTALL PACKAGES        ##
    #############################

    dpkg -i ${PKG_ZBX_NAME} > /dev/null
    $S_LOG -s $? -d $S_NAME "DPKG of ${PKG_ZBX_NAME} returned code $?"

    $S_DIR_PATH/ft-util/ft_util_pkg -u -i "zabbix-agent2" || exit 1

fi

#############################
## DEPLOY CONFIG FILE      ## 
#############################
$S_LOG -d $S_NAME "Zabbix Agent 2 configuration"

if [ -n "$1" ] && [ -n "$2" ]
then
    ZBX_SRV_PASSIVE=$1
    ZBX_SRV_ACTIVE=$2
else
    source <(grep "Server" ${ZBX_CONF})
    $S_LOG -s $? -d $S_NAME "Loaded ZBX_SRV_PASSIVE and ZBX_SRV_ACTIVE variable from ${ZBX_CONF}"
    ZBX_SRV_PASSIVE="${Server}"
    ZBX_SRV_ACTIVE="${ServerActive}"
    $S_LOG -d $S_NAME "ZBX_SRV_PASSIVE=\"${ZBX_SRV_PASSIVE}\""
    $S_LOG -d $S_NAME "ZBX_SRV_ACTIVE=\"${ZBX_SRV_ACTIVE}\""
fi

[ ! -e "${ZBX_CONF}.origin" ] && cp "${ZBX_CONF}" "${ZBX_CONF}.origin"

if [ ! -d "${ZBX_CONF_D}" ] ; then mkdir -pv "${ZBX_CONF_D}" ; $S_LOG -s $? -d $S_NAME "Creating ${ZBX_CONF_D} returned EXIT_CODE=$?" ; fi


mkdir -pv "/var/log/zabbix/" | $S_LOG -d "$S_NAME" -d "/var/log/zabbix/" -i
chown zabbix:zabbix "/var/log/zabbix/" | $S_LOG -d "$S_NAME" -d "/var/log/zabbix/" -i

echo "# Generated by ${S_NAME}
# $(date)
Hostname=$(hostname -f)
Server=${ZBX_SRV_PASSIVE}
ServerActive=${ZBX_SRV_ACTIVE}
PidFile=/var/run/zabbix/zabbix_agent2.pid
LogFile=/var/log/zabbix/zabbix_agent2.log
LogFileSize=0
ControlSocket=/tmp/agent.sock
Include=${ZBX_CONF_D}/*.conf" > ${ZBX_CONF}
cat $ZBX_CONF | $S_LOG -d "$S_NAME" -d "$ZBX_CONF" -i 

#############################
## ENABLE ZABBIX SERVICE   ##
#############################
systemctl enable zabbix-agent2 &>/dev/null
$S_LOG -s $? -d $S_NAME "systemctl enable zabbix-agent2 returned code $?" # for Debian 7 it will not work but the agent seems to install itself in /etc/rc2.d/

#############################
## RESTART ZABBIX SERVICE  ##
#############################
echo "systemctl restart zabbix-agent2" | at now + 1 min &>/dev/null ## restart zabbix agent with a delay
$S_LOG -s $? -d "$S_NAME" "Scheduling Zabbix Agent Restart"

$S_LOG -d "$S_NAME" "End $S_NAME"